### ISSUE TITLE
vmware-tanzu/carvel-setup-action@v1 disappeared 

### ISSUE THREAD

**Issue by wanis-fahmy** [carvel-dev/setup-action#262]
it seems that `vmware-tanzu/carvel-setup-action@v1` was removed somehow and replaced with `carvel-dev/setup-action@v1`

The action doesnt exist anymore and we get an error: Repository not found

We switched to `carvel-dev/setup-action@v1` and it works but the breaking change was not announced and the readme is still pointing to the old action.

**Comment by wanis-fahmy** [comment]
If confirmed that the switch is final, I can create a PR to update the old references :)

**Comment by praveenrewar** [comment]
Thanks for the callout @wanisfahmyDE. This is part of the ongoing effort to move to a vendor neutral organisation in light of Carvel being accepted as a CNCF Sandbox project ([Slack thread](https://kubernetes.slack.com/archives/CH8KCCKA5/p1673562341794759)). We might have missed a couple of things like this one during the migration and we will try to fix them ASAP.

> If confirmed that the switch is final, I can create a PR to update the old references :)

Yep, this is final. That will be great, thank you :)

**Comment by praveenrewar** [comment]
@wanisfahmyDE BTW, I was expecting this to work (because the redirections are working), can you tell more about the environment where you are using this, maybe redirections are disabled?

P.S. I will try to test this and see if the redirection is not helpful in this scenario.

**Update**: Redirect seems to be working. Tested it [here](https://github.com/carvel-dev/release-scripts/actions/runs/3966880916/jobs/6798199353#step:3:1).

**Comment by wanis-fahmy** [comment]
@praveenrewar redirection works when hitting links in the browser, but from our github actions workflows it didn't when we were still referencing the old path

**Comment by praveenrewar** [comment]
That is weird. I am not sure what could be causing it, but glad that `carvel-dev/setup-action@1` works for you.

**Comment by jbrunton** [comment]
I'm also seeing the redirects work as expected in a workflow (including the old `k14s` one): https://github.com/jbrunton/test-carvel-setup-action/blob/develop/.github/workflows/test.yml

@wanisfahmyDE : Out of curiosity, are you able to spot any differences between the above workflow and the one you're using which was causing problems?

Also, thank you for the PR!

**Comment by wanis-fahmy** [comment]
> I'm also seeing the redirects work as expected in a workflow (including the old `k14s` one): https://github.com/jbrunton/test-carvel-setup-action/blob/develop/.github/workflows/test.yml
> 
> @wanisfahmyDE : Out of curiosity, are you able to spot any differences between the above workflow and the one you're using which was causing problems?
> 
> Also, thank you for the PR!

Hey @jbrunton i'm not sure if that's the issue, but we're actually encapsulating the carvel action in another custom action that we provide in our org and this one is composite.

the error we get is:
```bash
Error: Unable to resolve actions. Repository not found: vmware-tanzu/carvel-setup-action
```

our action used to look like this:
```yaml
name: Deploy Helm Chart with kapp
description: Uses Carvel kapp to deploy a Helm chart with diffing and logs
inputs:
  release:
    description: Name of the Helm release that should be deployed
    required: true
    default: ${{github.event.repository.name}}
  chart:
    description: Path to or name of the chart that should be deployed
    required: true
  version:
    description: Version of the Helm chart that should be deployed
    required: true
  namespace:
    description: Kubernetes namespace into which the chart will be deployed
    required: true
    default: ${{github.event.repository.name}}
  set:
    description: A list of properties in dot notation and their values that should be passed to the Helm templating
    required: false
  value-files:
    description: A list of paths to YAML files containing values to be used by Helm templating, separated by commas
    required: false
  additional-helm-args:
    description: Additional CLI arguments that should be passed to the Helm template command
    required: false
runs:
  using: composite
  steps:
    - name: Setup Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.9.4

    - name: Setup kapp
      uses: vmware-tanzu/carvel-setup-action@v1
      with:
        only: kapp
        kapp: v0.53.0

    - name: Extract ECR charts
      uses: actions-ecosystem/action-regex-match@v2
      id: ecr-regex
      with:
        text: ${{inputs.chart}}
        regex: '^oci:\/\/([0-9]{12}.dkr.ecr.[a-z0-9-]+.amazonaws.com)\/.*$'
        flags: g

    - name: Login Helm for ECR
      if: steps.ecr-regex.outputs.match != ''
      shell: bash
      run: aws ecr get-login-password | helm registry login --username AWS --password-stdin ${{steps.ecr-regex.outputs.group1}}

    - name: Determine Helm flags
      uses: actions/github-script@v6
      id: helm-flags
      env:
        VALUE_FILES: ${{inputs.value-files}}
      with:
        result-encoding: string
        # language=JavaScript
        script: |
          const valueFiles = (process.env.VALUE_FILES ?? '')
              .split(',')
              .map(x => `-f ${x}`)
              .join(' ')          
          return valueFiles

    - name: Deploy
      env:
        FORCE_COLOR: '1'
      shell: bash
      run: helm template ${{inputs.release}} ${{inputs.chart}} --version ${{inputs.version}} -n ${{inputs.namespace}} --set '${{inputs.set}}' ${{steps.helm-flags.outputs.result}} ${{inputs.additional-helm-args}} | kapp deploy -n ${{inputs.namespace}} -c -y -a ${{inputs.release}} -f-
```
