### ISSUE TITLE
Exclude as Opposed to Only Approach for Which Carvel Tools to Install

### ISSUE THREAD

**Issue by danielhelfand** [carvel-dev/setup-action#90]
The carvel-setup-action currently supports an `only` option to specify which tools of the whole suite should be installed. While this is sufficient for solving the issue of only installing certain tools, it would also be helpful from a convenience perspective to be able to exclude tools so less tools could be specified in a circumstance where you want most but not all of the suite:

```
-name: Install Carvel Tools
  uses: vmware-tanzu/carvel-setup-action@v1
    with:
      token: ${{ secrets.GITHUB_TOKEN }}
      exclude: kwt
      ytt: v0.31.0
      kapp: v0.35.0
      kbld: v0.28.0
      imgpkg: v0.3.0
      vendir: v0.16.0
```

With `only`, the following would need to happen to avoid installing `kwt`:

```
-name: Install Carvel Tools
  uses: vmware-tanzu/carvel-setup-action@v1
    with:
      token: ${{ secrets.GITHUB_TOKEN }}
      only: ytt, kapp, kbld, imgpkg, vendir
      ytt: v0.31.0
      kapp: v0.35.0
      kbld: v0.28.0
      imgpkg: v0.3.0
      vendir: v0.16.0
```
